# Sponsorship and Funding

# AdminBolt is a commercial product. For licensing and enterprise support, please visit:
# https://adminbolt.com/pricing

# If you'd like to support the project:
custom: ['https://adminbolt.com/pricing', 'https://adminbolt.com/sponsor']

# For enterprise inquiries:
# enterprise@adminbolt.com

