# Sponsorship and Funding

# AdminBolt is a commercial product. For licensing and enterprise support, please visit:
# https://billing.adminbolt.com

# If you'd like to support the project:
custom: ['https://billing.adminbolt.com']

# For enterprise inquiries:
# contact@adminbolt.com

